name: Uribarri
favicon: null
layout_spectrum: 0.9666373385116458
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: sign-ups
    item: null
    url: null
typography_spectrum: 0.5449796011671424
